export const ACTION_NAMES = {
    CHANGE_NETWORK_STATUS: "CHANGE_NETWORK_STATUS",
    CHANGE_NETWORK_STATUS_SUCCESS: "CHANGE_NETWORK_STATUS_SUCCESS",
    CHANGE_NETWORK_STATUS_ERROR: "CHANGE_NETWORK_STATUS_ERROR",
    ADD_TASK: "ADD_TASK",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_ERROR: "ADD_TASK_ERROR",
    CHANGE_TASK_STATUS: "CHANGE_TASK_STATUS",
    CHANGE_TASK_STATUS_SUCCESS: "CHANGE_TASK_STATUS_SUCCESS",
    CHANGE_TASK_STATUS_ERROR: "CHANGE_TASK_STATUS_ERROR",
};
